library(data.table)
library(ape)
library(vegan)
library(phytools)
library(rbiom)
library(DESeq2)
library(plyr)
library(dplyr)
library(wordcloud)
library(RColorBrewer)
library(wordcloud)
library(wordcloud2)
library(tm)
library(NLP)
## NOTE: attach our in house packages last
library(plot.data)
source('/opt/rserve/lib/functions.R')
